use serde::{Deserialize, Serialize};

use crate::{ClientCommand, ProtocolVersion, SessionContext};

/// Coarse connection lifecycle exposed to headless and graphical frontends.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConnectionPhase {
    #[default]
    Disconnected,
    Connecting,
    Login,
    Configuration,
    Play,
    Closed,
}

/// Semantic input decoded from the network or generated by the session clock.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum ClientEvent {
    ConnectionPhaseChanged(ConnectionPhase),
    Tick,
    PlayerSpawned {
        entity_id: i32,
    },
    PositionSynchronized {
        position: [f64; 3],
        yaw: f32,
        pitch: f32,
    },
    HealthUpdated {
        health: f32,
        food: i32,
    },
    SelectedSlotChanged(u8),
    ChatReceived(String),
    Disconnected {
        reason: String,
    },
}

/// Explicit side effects requested by deterministic core logic.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum CoreEffect {
    CommandAccepted(ClientCommand),
}

/// Coherent immutable state consumed by presentation and diagnostics.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientSnapshot {
    pub protocol: ProtocolVersion,
    pub revision: u64,
    pub tick: u64,
    pub phase: ConnectionPhase,
    pub entity_id: Option<i32>,
    pub position: [f64; 3],
    pub yaw: f32,
    pub pitch: f32,
    pub health: f32,
    pub food: i32,
    pub selected_slot: u8,
    pub recent_chat: Vec<String>,
    pub disconnect_reason: Option<String>,
}

/// Single-owner deterministic state reducer.
#[derive(Clone, Debug)]
pub struct ClientCore {
    context: SessionContext,
    snapshot: ClientSnapshot,
}

impl ClientCore {
    #[must_use]
    pub fn new(context: SessionContext) -> Self {
        Self {
            context,
            snapshot: ClientSnapshot {
                protocol: context.protocol,
                revision: 0,
                tick: 0,
                phase: ConnectionPhase::Disconnected,
                entity_id: None,
                position: [0.0; 3],
                yaw: 0.0,
                pitch: 0.0,
                health: 20.0,
                food: 20,
                selected_slot: 0,
                recent_chat: Vec::new(),
                disconnect_reason: None,
            },
        }
    }

    #[must_use]
    pub const fn context(&self) -> SessionContext {
        self.context
    }

    #[must_use]
    pub fn snapshot(&self) -> &ClientSnapshot {
        &self.snapshot
    }

    /// Applies one semantic input atomically and advances the snapshot revision.
    pub fn apply_event(&mut self, event: ClientEvent) {
        match event {
            ClientEvent::ConnectionPhaseChanged(phase) => self.snapshot.phase = phase,
            ClientEvent::Tick => self.snapshot.tick = self.snapshot.tick.saturating_add(1),
            ClientEvent::PlayerSpawned { entity_id } => self.snapshot.entity_id = Some(entity_id),
            ClientEvent::PositionSynchronized {
                position,
                yaw,
                pitch,
            } => {
                self.snapshot.position = position;
                self.snapshot.yaw = yaw;
                self.snapshot.pitch = pitch;
            }
            ClientEvent::HealthUpdated { health, food } => {
                self.snapshot.health = health;
                self.snapshot.food = food;
            }
            ClientEvent::SelectedSlotChanged(slot) => self.snapshot.selected_slot = slot.min(8),
            ClientEvent::ChatReceived(message) => {
                self.snapshot.recent_chat.push(message);
                if self.snapshot.recent_chat.len() > 100 {
                    self.snapshot.recent_chat.remove(0);
                }
            }
            ClientEvent::Disconnected { reason } => {
                self.snapshot.phase = ConnectionPhase::Closed;
                self.snapshot.disconnect_reason = Some(reason);
            }
        }
        self.snapshot.revision = self.snapshot.revision.saturating_add(1);
    }

    /// Accepts one user command. Network encoding is deliberately an adapter
    /// concern because its packet representation varies by protocol profile.
    #[must_use]
    pub fn apply_command(&mut self, command: ClientCommand) -> Vec<CoreEffect> {
        if let ClientCommand::SetControls(controls) = &command {
            self.snapshot.yaw = controls.yaw;
            self.snapshot.pitch = controls.pitch;
            self.snapshot.selected_slot = controls.selected_slot.min(8);
        }
        self.snapshot.revision = self.snapshot.revision.saturating_add(1);
        vec![CoreEffect::CommandAccepted(command)]
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reducer_produces_coherent_monotonic_snapshots() {
        let mut core = ClientCore::new(SessionContext::new(ProtocolVersion::V1_21_5));
        core.apply_event(ClientEvent::PlayerSpawned { entity_id: 42 });
        core.apply_event(ClientEvent::PositionSynchronized {
            position: [1.0, 64.0, -2.0],
            yaw: 90.0,
            pitch: 5.0,
        });
        core.apply_event(ClientEvent::HealthUpdated {
            health: 17.5,
            food: 16,
        });
        let snapshot = core.snapshot();
        assert_eq!(snapshot.revision, 3);
        assert_eq!(snapshot.entity_id, Some(42));
        assert_eq!(snapshot.position, [1.0, 64.0, -2.0]);
        assert_eq!((snapshot.health, snapshot.food), (17.5, 16));
    }
}
