#!/usr/bin/env python3
"""Generate deduplicated per-state Java collision shapes from minecraft-data.

Usage:
    python3 scripts/generate_collision.py \
      1_20_1 blocks-1.20.json blockCollisionShapes-1.20.json \
      [<suffix> <blocks.json> <blockCollisionShapes.json> ...]

The collision source is produced by PrismarineJS/minecraft-data-generator from
the vanilla game's voxel shapes. Output is committed Rust, so runtime builds do
not download or bundle third-party data files.
"""

import json
import sys


def rust_float(value: object) -> str:
    number = float(value)
    text = repr(number)
    return text if "." in text or "e" in text.lower() else text + ".0"


def main() -> None:
    if len(sys.argv) < 4 or (len(sys.argv) - 1) % 3:
        sys.exit(
            "usage: generate_collision.py "
            "<suffix> <blocks.json> <blockCollisionShapes.json> [...]"
        )

    profiles = []
    union_shapes: list[tuple[tuple[float, ...], ...]] = []
    union_ids: dict[tuple[tuple[float, ...], ...], int] = {}

    for index in range(1, len(sys.argv), 3):
        suffix, blocks_path, collision_path = sys.argv[index : index + 3]
        with open(blocks_path) as file:
            blocks = json.load(file)
        with open(collision_path) as file:
            collision = json.load(file)

        max_state = max(block["maxStateId"] for block in blocks)
        state_shapes = [0] * (max_state + 1)
        assigned = [False] * (max_state + 1)
        for block in blocks:
            name = block["name"]
            if name not in collision["blocks"]:
                raise ValueError(f"{suffix}: collision data missing block {name}")
            references = collision["blocks"][name]
            state_count = block["maxStateId"] - block["minStateId"] + 1
            if not isinstance(references, list):
                references = [references] * state_count
            if len(references) != state_count:
                raise ValueError(
                    f"{suffix}: {name} has {state_count} states but "
                    f"{len(references)} collision references"
                )
            for offset, source_id in enumerate(references):
                source_shape = collision["shapes"][str(source_id)]
                shape = tuple(tuple(float(value) for value in box) for box in source_shape)
                if len(shape) > 16:
                    raise ValueError(f"{suffix}: shape {source_id} exceeds 16 boxes")
                union_id = union_ids.get(shape)
                if union_id is None:
                    union_id = len(union_shapes)
                    if union_id > 0xFFFF:
                        raise ValueError("deduplicated shape count exceeds u16")
                    union_ids[shape] = union_id
                    union_shapes.append(shape)
                state = block["minStateId"] + offset
                state_shapes[state] = union_id
                assigned[state] = True
        if not all(assigned):
            missing = assigned.index(False)
            raise ValueError(f"{suffix}: global state {missing} was not assigned")
        profiles.append((suffix, state_shapes))

    flat_boxes = []
    shape_ranges = []
    for shape in union_shapes:
        shape_ranges.append((len(flat_boxes), len(shape)))
        flat_boxes.extend(shape)

    lines = [
        "// @generated by scripts/generate_collision.py from PrismarineJS minecraft-data",
        "// blockCollisionShapes.json. DO NOT EDIT BY HAND.",
        "",
        "use super::CollisionBox;",
        "",
        "#[rustfmt::skip]",
        "pub static COLLISION_BOXES: &[CollisionBox] = &[",
    ]
    for box_values in flat_boxes:
        values = [rust_float(value) for value in box_values]
        lines.append(
            "    CollisionBox { min: ["
            + ", ".join(values[:3])
            + "], max: ["
            + ", ".join(values[3:])
            + "] },"
        )
    lines.extend(["];", "", "#[rustfmt::skip]", "pub static COLLISION_SHAPES: &[(u32, u8)] = &["])
    for start, length in shape_ranges:
        lines.append(f"    ({start}, {length}),")
    lines.extend(["];", ""])

    for suffix, state_shapes in profiles:
        lines.extend(
            [
                "#[rustfmt::skip]",
                f"pub static COLLISION_STATES_{suffix}: &[u16] = &[",
            ]
        )
        for start in range(0, len(state_shapes), 32):
            chunk = state_shapes[start : start + 32]
            lines.append("    " + ", ".join(str(value) for value in chunk) + ",")
        lines.extend(["];", ""])

    sys.stdout.write("\n".join(lines))


if __name__ == "__main__":
    main()
