#!/usr/bin/env python3
"""Generate crab-registry's item table from minecraft-data's items.json.

Usage: python3 scripts/generate_items.py path/to/items.json > src/items_1_20_1.rs
"""
import json
import sys


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit("usage: generate_items.py <items.json>")
    with open(sys.argv[1]) as f:
        items = json.load(f)
    items.sort(key=lambda e: e["id"])

    lines = [
        "// @generated by scripts/generate_items.py from PrismarineJS minecraft-data",
        "// (Minecraft 1.20.1). DO NOT EDIT BY HAND.",
        "",
        "use super::ItemDef;",
        "",
        "/// Every item for 1.20.1, sorted by id.",
        "pub static ITEMS_1_20_1: &[ItemDef] = &[",
    ]
    for e in items:
        stack = min(int(e.get("stackSize", 64)), 255)
        lines.append(
            f'    ItemDef {{ id: {e["id"]}, name: "{e["name"]}", '
            f"stack_size: {stack} }},"
        )
    lines.append("];")
    lines.append("")
    sys.stdout.write("\n".join(lines))


if __name__ == "__main__":
    main()
