#!/usr/bin/env python3
"""Generate crab-registry's block table from minecraft-data's blocks.json.

Usage:
    python3 scripts/generate_blocks.py path/to/blocks.json > src/blocks_1_20_1.rs

Source data: https://github.com/PrismarineJS/minecraft-data (data/pc/1.20/blocks.json),
which is derived from the vanilla data-generator reports. The output is committed
so the crate has no build-time or runtime dependencies.
"""
import json
import sys


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit("usage: generate_blocks.py <blocks.json>")
    with open(sys.argv[1]) as f:
        blocks = json.load(f)

    blocks.sort(key=lambda b: b["minStateId"])

    lines = [
        "// @generated by scripts/generate_blocks.py from PrismarineJS minecraft-data",
        "// (Minecraft 1.20.1, protocol 763). DO NOT EDIT BY HAND.",
        "",
        "use super::BlockDef;",
        "",
        "/// Every block for protocol 763, sorted by `min_state`. State-ID ranges are",
        "/// contiguous and disjoint, so binary search over `min_state` resolves any state.",
        "pub static BLOCKS_1_20_1: &[BlockDef] = &[",
    ]
    for b in blocks:
        name = "minecraft:" + b["name"]
        hardness = float(b.get("hardness") if b.get("hardness") is not None else -1.0)
        needs_tool = "true" if b.get("harvestTools") else "false"
        lines.append(
            f'    BlockDef {{ name: "{name}", min_state: {b["minStateId"]}, '
            f'max_state: {b["maxStateId"]}, default_state: {b["defaultState"]}, '
            f"hardness: {hardness}, needs_tool: {needs_tool} }},"
        )
    lines.append("];")
    lines.append("")
    sys.stdout.write("\n".join(lines))


if __name__ == "__main__":
    main()
