#!/usr/bin/env python3
"""Generate crab-registry's entity table from minecraft-data's entities.json.

Usage: python3 scripts/generate_entities.py path/to/entities.json 1_20_3 > src/entities_1_20_3.rs
"""
import json
import sys


def main() -> None:
    if len(sys.argv) not in (2, 3):
        sys.exit("usage: generate_entities.py <entities.json> [version_suffix]")
    suffix = sys.argv[2] if len(sys.argv) == 3 else "1_20_1"
    label = suffix.replace("_", ".")
    with open(sys.argv[1]) as f:
        entities = json.load(f)
    entities.sort(key=lambda e: e["id"])

    lines = [
        "// @generated by scripts/generate_entities.py from PrismarineJS minecraft-data",
        f"// (Minecraft {label}). DO NOT EDIT BY HAND.",
        "",
        "use super::EntityDef;",
        "",
        f"/// Every entity type for {label}, sorted by id.",
        f"pub static ENTITIES_{suffix}: &[EntityDef] = &[",
    ]
    for e in entities:
        lines.append(
            f'    EntityDef {{ id: {e["id"]}, name: "{e["name"]}", '
            f'width: {float(e["width"])}, height: {float(e["height"])} }},'
        )
    lines.append("];")
    lines.append("")
    sys.stdout.write("\n".join(lines))


if __name__ == "__main__":
    main()
