#!/usr/bin/env python3
"""Generate crab-registry's item table from minecraft-data's items.json.

Usage: python3 scripts/generate_items.py path/to/items.json 1_20_3 > src/items_1_20_3.rs
"""
import json
import sys


def main() -> None:
    if len(sys.argv) not in (2, 3):
        sys.exit("usage: generate_items.py <items.json> [version_suffix]")
    suffix = sys.argv[2] if len(sys.argv) == 3 else "1_20_1"
    label = suffix.replace("_", ".")
    with open(sys.argv[1]) as f:
        items = json.load(f)
    items.sort(key=lambda e: e["id"])

    lines = [
        "// @generated by scripts/generate_items.py from PrismarineJS minecraft-data",
        f"// (Minecraft {label}). DO NOT EDIT BY HAND.",
        "",
        "use super::ItemDef;",
        "",
        f"/// Every item for {label}, sorted by id.",
        f"pub static ITEMS_{suffix}: &[ItemDef] = &[",
    ]
    for e in items:
        stack = min(int(e.get("stackSize", 64)), 255)
        lines.append(
            f'    ItemDef {{ id: {e["id"]}, name: "{e["name"]}", '
            f"stack_size: {stack} }},"
        )
    lines.append("];")
    lines.append("")
    sys.stdout.write("\n".join(lines))


if __name__ == "__main__":
    main()
