#!/usr/bin/env python3
"""Generate crab-registry's entity table from minecraft-data's entities.json.

Usage: python3 scripts/generate_entities.py path/to/entities.json > src/entities_1_20_1.rs
"""
import json
import sys


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit("usage: generate_entities.py <entities.json>")
    with open(sys.argv[1]) as f:
        entities = json.load(f)
    entities.sort(key=lambda e: e["id"])

    lines = [
        "// @generated by scripts/generate_entities.py from PrismarineJS minecraft-data",
        "// (Minecraft 1.20.1). DO NOT EDIT BY HAND.",
        "",
        "use super::EntityDef;",
        "",
        "/// Every entity type for 1.20.1, sorted by id.",
        "pub static ENTITIES_1_20_1: &[EntityDef] = &[",
    ]
    for e in entities:
        lines.append(
            f'    EntityDef {{ id: {e["id"]}, name: "{e["name"]}", '
            f'width: {float(e["width"])}, height: {float(e["height"])} }},'
        )
    lines.append("];")
    lines.append("")
    sys.stdout.write("\n".join(lines))


if __name__ == "__main__":
    main()
